name: itam_app
description: ITAM - IT Asset Management Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.6.2

  # Network
  dio: ^5.7.0

  # Local storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3

  # Utilities
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  intl: ^0.20.1
  dart_jsonwebtoken: ^2.14.0
  path_provider: ^2.1.4

  # Qr code
  mobile_scanner: ^6.0.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  share_plus: ^12.0.2
  printing: ^5.13.1
  gal: ^2.3.0
  flutter_zxing: ^1.8.0
  pdf: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

  # Code generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/